
public class Test {

	public static void main(String[] args) {
		
		System.out.println("Main Starts...");
		
		int num1 = 10, num2 = 0, num3 = 0;
		int arr[] = {100, 200, 300, 400};
		
		try {
			System.out.println("try starts...");
			num3 = num1 / num2;
			System.out.println("Num3" + num3);
			System.out.println("try end...");
		}catch(ArithmeticException ae) {
			System.out.println("Inside ArithmeticException");
			System.out.println(ae.getMessage());
			System.out.println("Numerator cannot be Zero!");
		}
		
		System.out.println(arr[4]);
		System.out.println("Main End...");
		
	}

}
